#!/usr/bin/env bash
# sync-from-cowork.sh — one-way sync from the Cowork scaffold into this WSL repo.
#
# Cowork (Claude desktop) writes to a folder on your Windows P: drive; this pulls
# those updates into the WSL git working copy so you can review + commit. The
# scaffold is the source of truth; this is explicitly one-way (never writes back).
# Mirrors cloud/edge's sync-from-cowork.sh.
#
# Usage:
#   bash scripts/sync-from-cowork.sh            # quiet sync (count + errors only)
#   bash scripts/sync-from-cowork.sh --verbose  # also list every transferred file
#   bash scripts/sync-from-cowork.sh --dry      # show what WOULD change
#   bash scripts/sync-from-cowork.sh --delete   # also remove local files missing
#                                                  in the scaffold (CAREFUL)
#
# Configure via env:
#   BLUEPADEL_BRAND_SRC  default: /mnt/p/Claude/Projects/Internal/Padel/bluepadel-brand
set -euo pipefail

SRC="${BLUEPADEL_BRAND_SRC:-/mnt/p/Claude/Projects/Internal/Padel/bluepadel-brand}"
DST="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yel()   { printf '\033[33m%s\033[0m\n' "$*"; }
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }

mode="sync"
delete_flag=""
verbose=0
while [ $# -gt 0 ]; do
    case "$1" in
        --dry|-n)      mode="dry" ;;
        --delete)      delete_flag="--delete-after" ;;
        --verbose|-v)  verbose=1 ;;
        --help|-h)     sed -n '2,18p' "${BASH_SOURCE[0]}" | sed 's/^# //;s/^#$//'; exit 0 ;;
        *) red "Unknown arg: $1"; exit 2 ;;
    esac
    shift
done

[ -d "$SRC" ] || { red "Scaffold source not found: $SRC"; yel "Override with BLUEPADEL_BRAND_SRC=/mnt/p/..."; exit 1; }
command -v rsync >/dev/null 2>&1 || { red "rsync not installed"; yel "  sudo apt-get install -y rsync"; exit 1; }

EXCLUDES=(
    --exclude=.git/
    --exclude=node_modules/
    --exclude=dist/                 # tsup build output — regenerated by `npm run build`
    --exclude=package-lock.json     # WSL owns the lock (npm install manages it)
    --exclude=.env
    --exclude='.env.*'
    --exclude='*.swp'
    --exclude='.~lock.*'
    --exclude='~$*'
)

run_rsync() {
    local extra_args=("$@") tmp_out tmp_err rc n
    tmp_out=$(mktemp); tmp_err=$(mktemp)
    if rsync -ai --info=stats0 "${extra_args[@]}" "${EXCLUDES[@]}" $delete_flag \
            "$SRC/" "$DST/" >"$tmp_out" 2>"$tmp_err"; then rc=0; else rc=$?; fi
    n=$(grep -cE '^[<>ch.*][fdLD]' "$tmp_out" || true)
    if (( rc != 0 )); then red "  rsync failed (rc=$rc):"; sed 's/^/    /' "$tmp_err"; rm -f "$tmp_out" "$tmp_err"; return "$rc"; fi
    if (( verbose == 1 )) && [ -s "$tmp_out" ]; then sed 's/^/    /' "$tmp_out"; fi
    if (( n == 0 )); then green "  Sync OK — 0 files changed"; else green "  Sync OK — ${n} file(s) updated"; fi
    rm -f "$tmp_out" "$tmp_err"
}

# Strip stray NUL bytes the cowork mount can inject into text files mid-write.
strip_nulls() {
    python3 - "$DST" <<'PY'
import pathlib, sys
root = pathlib.Path(sys.argv[1])
exts = {".ts", ".tsx", ".js", ".mjs", ".cjs", ".json", ".css", ".md", ".yml", ".yaml"}
n = 0
for p in root.rglob("*"):
    if "node_modules" in p.parts or ".git" in p.parts or "dist" in p.parts:
        continue
    if not p.is_file() or p.suffix not in exts:
        continue
    try:
        data = p.read_bytes()
    except OSError:
        continue
    if b"\x00" in data:
        p.write_bytes(data.replace(b"\x00", b"")); n += 1
        print(f"  stripped nulls: {p.relative_to(root)}")
if n:
    print(f"  Stripped null bytes from {n} file(s)")
PY
}

# Fail loud if the mount truncated a synced .json / .mjs / .js mid-write
# (a tail-truncated file has no NULs — it just fails to parse). .ts is covered
# by `npm run typecheck`. Scoped to files this sync actually changed.
verify_integrity() {
    command -v git >/dev/null 2>&1 && [ -d "$DST/.git" ] || return 0
    cd "$DST"
    local changed
    changed=$(git status --porcelain --untracked-files=all | sed 's/^...//' | tr -d '"' || true)
    [ -z "$changed" ] && return 0
    local bad=0
    while IFS= read -r f; do
        [ -n "$f" ] && [ -f "$f" ] || continue
        case "$f" in
            *.json) node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "$f" 2>/dev/null || { red "  INTEGRITY FAIL (JSON): $f"; bad=1; } ;;
            *.mjs|*.cjs|*.js) node --check "$f" 2>/dev/null || { red "  INTEGRITY FAIL (parse): $f"; bad=1; } ;;
        esac
    done <<< "$changed"
    if (( bad )); then red "  Synced files don't parse (likely truncated by the cowork mount). Re-run the sync."; return 3; fi
    green "  Integrity OK — changed .json/.js parse cleanly"
}

show_git_summary() {
    command -v git >/dev/null 2>&1 && [ -d "$DST/.git" ] || return 0
    cd "$DST"
    local n; n=$(git status --porcelain | wc -l)
    if [ "$n" -gt 0 ]; then
        yel "  $n local change(s) after sync. Review:"
        set +o pipefail; git status --short | head -30; set -o pipefail
        [ "$n" -gt 30 ] && yel "  …and $((n - 30)) more"
    else
        green "  No local changes — already up to date."
    fi
}

case "$mode" in
    dry)
        bold "DRY-RUN — would sync"; echo "  $SRC"; echo "to"; echo "  $DST"
        verbose=1; run_rsync "--dry-run" ;;
    sync)
        bold "Syncing scaffold → working copy"
        run_rsync; strip_nulls; verify_integrity; echo; show_git_summary ;;
esac
